version: 2
updates:
  # Update Go modules dependencies
  - package-ecosystem: "gomod"
    directory: "/" # Location of your go.mod file
    schedule:
      interval: "weekly" # Check for updates every week
    commit-message:
      prefix: "chore" # Prefix for commit messages
    open-pull-requests-limit: 5 # Limit the number of open PRs at any time

  # Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your GitHub Actions workflows
    schedule:
      interval: "weekly" # Check for updates every week
    commit-message:
      prefix: "chore" # Prefix for commit messages
    open-pull-requests-limit: 5
